# Generated by Django 4.2.6 on 2024-03-15 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_apihitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apihitcount',
            name='api_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
