# Generated by Django 4.2.6 on 2024-03-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_apihitcount_api_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apihitcount',
            name='api_code',
            field=models.CharField(max_length=255),
        ),
    ]
