# Generated by Django 4.2.6 on 2024-03-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_team_api_code_alter_apihitcount_api_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='vedantsomani210474@acropolis.in', max_length=254),
        ),
    ]
